# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Topup(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, hash: str=None, status: str=None):  # noqa: E501
        """Topup - a model defined in Swagger

        :param hash: The hash of this Topup.  # noqa: E501
        :type hash: str
        :param status: The status of this Topup.  # noqa: E501
        :type status: str
        """
        self.swagger_types = {
            'hash': str,
            'status': str
        }

        self.attribute_map = {
            'hash': 'hash',
            'status': 'status'
        }
        self._hash = hash
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'Topup':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Topup of this Topup.  # noqa: E501
        :rtype: Topup
        """
        return util.deserialize_model(dikt, cls)

    @property
    def hash(self) -> str:
        """Gets the hash of this Topup.

        hash de la transacción.  # noqa: E501

        :return: The hash of this Topup.
        :rtype: str
        """
        return self._hash

    @hash.setter
    def hash(self, hash: str):
        """Sets the hash of this Topup.

        hash de la transacción.  # noqa: E501

        :param hash: The hash of this Topup.
        :type hash: str
        """

        self._hash = hash

    @property
    def status(self) -> str:
        """Gets the status of this Topup.

        resultado de la transacción.  # noqa: E501

        :return: The status of this Topup.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Topup.

        resultado de la transacción.  # noqa: E501

        :param status: The status of this Topup.
        :type status: str
        """

        self._status = status
