# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Transaction(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, transaction: str=None):  # noqa: E501
        """Transaction - a model defined in Swagger

        :param transaction: The transaction of this Transaction.  # noqa: E501
        :type transaction: str
        """
        self.swagger_types = {
            'transaction': str
        }

        self.attribute_map = {
            'transaction': 'transaction'
        }
        self._transaction = transaction

    @classmethod
    def from_dict(cls, dikt) -> 'Transaction':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Transaction of this Transaction.  # noqa: E501
        :rtype: Transaction
        """
        return util.deserialize_model(dikt, cls)

    @property
    def transaction(self) -> str:
        """Gets the transaction of this Transaction.

        detalles de una transacción.  # noqa: E501

        :return: The transaction of this Transaction.
        :rtype: str
        """
        return self._transaction

    @transaction.setter
    def transaction(self, transaction: str):
        """Sets the transaction of this Transaction.

        detalles de una transacción.  # noqa: E501

        :param transaction: The transaction of this Transaction.
        :type transaction: str
        """

        self._transaction = transaction
